# Generated by Django 4.0.3 on 2022-04-13 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hesab', '0008_alter_shopping_day_hesab'),
    ]

    operations = [
        migrations.AddField(
            model_name='hesab',
            name='week',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='weekhesab', to='hesab.week'),
        ),
    ]
