# Generated by Django 4.0.3 on 2022-04-14 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hesab', '0009_hesab_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='week',
            name='sum',
            field=models.IntegerField(default=0),
        ),
    ]
