# Generated by Django 4.0.3 on 2022-04-15 18:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hesab', '0010_week_sum'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainHesab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('negative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usermainhesab_n', to=settings.AUTH_USER_MODEL)),
                ('plus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usermainhesab_p', to=settings.AUTH_USER_MODEL)),
                ('week', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='weekmainhesab', to='hesab.week')),
            ],
        ),
    ]
