# Generated by Django 4.0.3 on 2022-04-15 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hesab', '0011_mainhesab'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainhesab',
            name='amount',
            field=models.IntegerField(null=True),
        ),
    ]
